version: '3'

services:
  go-template:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: sh -c 'sleep 5 && go run ./main.go'

  go-template-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - mysql
    command: sh -c 'sleep 5 && go run ./main.go'

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todoapp
      MYSQL_USER: guest
      MYSQL_PASSWORD: Guest0000!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
